<script lang="ts">
  import { onMount } from 'svelte'
  import { Events } from '@wailsio/runtime'

  export type Backlink = {
    linkKind: 'page' | 'block-ref' | 'embed'
    sourceNotebook: string
    sourceSection: string
    sourcePage: string
    sourceBlockId: string
    snippet: string
    source?: string
  }

  interface Props {
    notebook: string
    section: string
    page: string
  }

  let { notebook, section, page }: Props = $props()
  let backlinks = $state<Backlink[]>([])
  let loading = $state(false)
  let error = $state('')
  let request = 0
  let refreshTimer: ReturnType<typeof setTimeout> | null = null

  const groups = $derived.by(() => {
    const grouped = new Map<string, { key: string; links: Backlink[] }>()
    for (const link of backlinks) {
      const key = `${link.sourceNotebook}\u0000${link.sourceSection}\u0000${link.sourcePage}`
      const current = grouped.get(key)
      if (current) current.links.push(link)
      else grouped.set(key, { key, links: [link] })
    }
    return [...grouped.values()]
  })

  const countLabel = $derived(
    groups.length === 1
      ? '1 page links here'
      : `${groups.length} pages link here`
  )

  async function getBacklinks(
    activeNotebook: string,
    activeSection: string,
    activePage: string
  ): Promise<Backlink[]> {
    // The binding is generated by the parallel backend work. Keeping this lazy
    // lets this panel type-check before that generated file is refreshed.
    const bindings =
      (await import('../../bindings/silt/app.js')) as unknown as {
        GetBacklinks: (
          notebook: string,
          section: string,
          page: string
        ) => Promise<Backlink[] | null>
      }
    return (
      (await bindings.GetBacklinks(
        activeNotebook,
        activeSection,
        activePage
      )) ?? []
    )
  }

  async function load(): Promise<void> {
    const sequence = ++request
    if (!notebook || !page) {
      backlinks = []
      error = ''
      loading = false
      return
    }
    loading = true
    try {
      const result = await getBacklinks(notebook, section, page)
      if (sequence !== request) return
      backlinks = result
      error = ''
    } catch (cause) {
      if (sequence !== request) return
      error =
        cause instanceof Error
          ? cause.message
          : 'Backlinks could not be loaded.'
    } finally {
      if (sequence === request) loading = false
    }
  }

  function openPage(link: Backlink): void {
    window.dispatchEvent(
      new CustomEvent('navigate-to-page', {
        detail: {
          notebook: link.sourceNotebook,
          section: link.sourceSection,
          page: link.sourcePage
        }
      })
    )
  }

  function openReference(link: Backlink): void {
    if (!link.sourceBlockId) {
      openPage(link)
      return
    }
    window.dispatchEvent(
      new CustomEvent('navigate-to-block', {
        detail: {
          notebook: link.sourceNotebook,
          section: link.sourceSection,
          page: link.sourcePage,
          blockId: link.sourceBlockId
        }
      })
    )
  }

  function kindLabel(kind: Backlink['linkKind']): string {
    if (kind === 'block-ref') return 'Block reference'
    if (kind === 'embed') return 'Embed'
    return 'Page link'
  }

  function kindMark(kind: Backlink['linkKind']): string {
    if (kind === 'block-ref') return '(('
    if (kind === 'embed') return '{{'
    return '[['
  }

  onMount(() => {
    const offBlock = Events.On('block:changed', () => {
      if (refreshTimer) clearTimeout(refreshTimer)
      refreshTimer = setTimeout(() => void load(), 200)
    })
    return () => {
      request++
      if (refreshTimer) clearTimeout(refreshTimer)
      offBlock()
    }
  })

  $effect(() => {
    void notebook
    void section
    void page
    void load()
  })
</script>

<nav
  aria-label="Backlinks to current page"
  class="flex-grow flex flex-col min-h-0 bg-surface-sidebar"
>
  <header
    class="px-3 py-3 border-b border-surface-sidebar-border flex-shrink-0"
  >
    <div class="flex items-center gap-2">
      <span
        class="material-symbols-outlined text-accent-primary-start text-type-2xl"
        aria-hidden="true">hub</span
      >
      <div class="min-w-0">
        <h2 class="font-headline-md text-headline-md text-text-primary">
          Backlinks
        </h2>
        <p
          class="m-0 text-type-2xs text-surface-sidebar-text-muted font-label-sm"
          aria-live="polite"
          aria-atomic="true"
        >
          {loading ? 'Refreshing backlinks…' : countLabel}
        </p>
      </div>
    </div>
  </header>

  <div class="flex-grow overflow-y-auto custom-scrollbar p-2">
    {#if !notebook || !page}
      <div class="text-center px-4 py-10 text-text-muted">
        <span
          class="material-symbols-outlined text-icon-2xl opacity-60"
          aria-hidden="true">draft</span
        >
        <p class="mt-2 text-text-primary font-label-sm-bold">
          Open a page first
        </p>
        <p class="mt-1 text-type-xs leading-relaxed">
          Backlinks follow the page you are viewing.
        </p>
      </div>
    {:else if error}
      <div
        class="m-1 p-3 rounded-lg border border-status-warn/35 bg-status-warn/10"
        role="alert"
      >
        <p class="m-0 text-type-xs text-text-primary">
          Backlinks could not be refreshed.
        </p>
        <button
          type="button"
          class="mt-2 p-0 border-none bg-transparent text-accent-primary-start text-type-xs underline cursor-pointer focus-visible:ring-2 focus-visible:ring-accent-primary-start rounded"
          onclick={() => void load()}>Try again</button
        >
      </div>
    {:else if !loading && groups.length === 0}
      <div class="text-center px-4 py-10 text-text-muted">
        <span
          class="material-symbols-outlined text-icon-2xl opacity-60"
          aria-hidden="true">link_off</span
        >
        <p class="mt-2 text-text-primary font-label-sm-bold">
          No pages link here yet
        </p>
        <p class="mt-1 text-type-xs leading-relaxed">
          Link this page with <code class="text-accent-secondary-start"
            >[[page]]</code
          >
          or reference one of its blocks with
          <code class="text-accent-secondary-start">((block))</code>.
        </p>
      </div>
    {:else}
      <div class="flex flex-col gap-2">
        {#each groups as group (group.key)}
          {@const source = group.links[0]}
          <section
            class="rounded-lg border border-surface-sidebar-border bg-surface-panel/35 overflow-hidden"
          >
            <h3 class="m-0">
              <button
                type="button"
                class="w-full px-2.5 py-2 border-none bg-transparent text-left flex items-center gap-2 text-surface-sidebar-text hover:bg-hover cursor-pointer transition-colors focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-accent-primary-start"
                onclick={() => openPage(source)}
                aria-label={`Open page ${source.sourcePage}`}
              >
                <span
                  class="material-symbols-outlined text-icon-md text-accent-primary-start"
                  aria-hidden="true">description</span
                >
                <span class="min-w-0 flex-1">
                  <span class="block truncate font-label-sm-bold text-label-sm"
                    >{source.sourcePage}</span
                  >
                  <span
                    class="block truncate text-type-3xs text-surface-sidebar-text-muted"
                  >
                    {[source.sourceNotebook, source.sourceSection]
                      .filter(Boolean)
                      .join(' / ')}
                  </span>
                </span>
                <span
                  class="text-type-3xs text-surface-sidebar-text-muted"
                  aria-label={`${group.links.length} references`}
                  >{group.links.length}</span
                >
              </button>
            </h3>
            <ul
              class="m-0 p-0 list-none border-t border-surface-sidebar-border/70"
            >
              {#each group.links as link, index (`${link.linkKind}:${link.sourceBlockId}:${index}`)}
                <li>
                  <button
                    type="button"
                    class="group w-full px-2.5 py-2 border-none bg-transparent text-left flex items-start gap-2 hover:bg-hover cursor-pointer transition-colors focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-accent-primary-start"
                    onclick={() => openReference(link)}
                    aria-label={`${link.sourceBlockId ? 'Jump to' : 'Open'} ${kindLabel(link.linkKind).toLowerCase()} in ${link.sourcePage}: ${link.snippet}`}
                  >
                    <span
                      class="mt-0.5 min-w-7 text-center rounded bg-accent-primary-start/10 text-accent-primary-start font-mono text-type-2xs font-bold"
                      title={kindLabel(link.linkKind)}
                      aria-hidden="true">{kindMark(link.linkKind)}</span
                    >
                    <span class="min-w-0 flex-1">
                      <span
                        class="block text-type-3xs uppercase tracking-wider text-surface-sidebar-text-muted font-label-sm-bold"
                      >
                        {kindLabel(link.linkKind)}
                      </span>
                      <span
                        class="block mt-0.5 text-type-xs text-surface-sidebar-text leading-snug line-clamp-3"
                      >
                        {link.snippet || 'Reference in this page'}
                      </span>
                    </span>
                    <span
                      class="material-symbols-outlined text-icon-sm text-surface-sidebar-text-muted group-hover:text-accent-primary-start"
                      aria-hidden="true"
                    >
                      {link.sourceBlockId ? 'my_location' : 'arrow_forward'}
                    </span>
                  </button>
                </li>
              {/each}
            </ul>
          </section>
        {/each}
      </div>
    {/if}
  </div>
</nav>
