//go:build tools

// Command genenums parses the four canonical Go typed-const enum blocks and
// emits one TypeScript module (frontend/src/generated/enums.ts) so the frontend
// consumes generated values instead of re-typing bare string literals.
//
// Why a parallel generator (not Wails's own `wails3 generate bindings`)? Wails
// v3 only emits typed-const enums when the named type is reachable from a bound
// service method's type graph. These four families are not reachable there:
// AIProviderType/AIErrorKind are reachable only through error-returning types
// (serialized as strings), IPCErrorCode lives on *IPCError (an error type), and
// EventName is a pure constant set with no struct field. Forcing reachability
// would pollute the IPC surface that cmd/inventory gates. Parsing the Go const
// blocks directly (go/ast) keeps the IPC surface clean and Go the single source
// of truth. See docs/decisions/ for the full ADR.
//
// Modes (selected by flag):
//
//	# Print the generated module to stdout (ad-hoc inspection):
//	go run -tags tools ./cmd/genenums/
//
//	# Write the module to the committed FE path (regenerate after an intentional
//	# enum change). Re-run -compare afterwards to confirm parity.
//	go run -tags tools ./cmd/genenums/ -update frontend/src/generated/enums.ts
//
//	# CI drift gate: regenerate to memory and compare against the committed file;
//	# exit 1 on any drift (a Go const changed/added/removed without regenerating).
//	go run -tags tools ./cmd/genenums/ -compare frontend/src/generated/enums.ts
//
// The output is deterministic (consts are emitted in source order), so the drift
// gate is byte-stable across platforms.
package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// enumSource pairs a Go named type with the file that declares its const block.
// Order controls the TS export order (stable).
var enumSources = []enumSource{
	{GoType: "AIProviderType", File: "backend/ai/service.go"},
	{GoType: "AIErrorKind", File: "backend/ai/service.go"},
	{GoType: "IPCErrorCode", File: "ipc_errors.go"},
	{GoType: "EventName", File: "events.go"},
}

type enumSource struct {
	GoType string
	File   string
}

// constEntry is one Go const (Name → string Value) belonging to an enum type.
type constEntry struct {
	Name  string
	Value string
}

func main() {
	out := flag.String("update", "", "write the generated module to this path (regenerate after an intentional enum change)")
	compare := flag.String("compare", "", "compare the generated module against the file at this path; exit 1 on drift")
	flag.Usage = func() {
		fmt.Fprintf(flag.CommandLine.Output(),
			"usage: genenums [flags] [repo-root]\n\n  flags:\n    -update <path>\n    -compare <path>\n")
		flag.PrintDefaults()
	}
	flag.Parse()
	root := flag.Arg(0)
	if root == "" {
		root = "."
	}

	module, err := generate(root)
	if err != nil {
		fmt.Fprintln(os.Stderr, "genenums:", err)
		os.Exit(1)
	}

	switch {
	case *out != "":
		if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
			fmt.Fprintln(os.Stderr, "genenums: mkdir:", err)
			os.Exit(1)
		}
		if err := os.WriteFile(*out, []byte(module), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "genenums: write:", err)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "genenums: module written to %s\n", *out)
	case *compare != "":
		want, err := os.ReadFile(*compare)
		if err != nil {
			fmt.Fprintln(os.Stderr, "genenums: read fixture:", err)
			os.Exit(1)
		}
		// Byte-strict compare: the generator emits Prettier-formatted output,
		// so any byte-level difference is a real drift — a Go const was added,
		// removed, renamed, reordered, or had its value changed without
		// regenerating the module. With formatting aligned to .prettierrc,
		// formatter churn can no longer mask a const change, so we no longer
		// normalize away whitespace/commas/quote style.
		if string(want) != module {
			fmt.Fprintf(os.Stderr,
				"genenums: DRIFT — %s does not match the generated module.\n"+
					"Regenerate with: go run -tags tools ./cmd/genenums/ -update %s\n",
				*compare, *compare)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "genenums: %s up to date\n", *compare)
	default:
		fmt.Print(module)
	}
}

// generate builds the TS module string from the four Go const blocks under root.
func generate(root string) (string, error) {
	var b strings.Builder
	b.WriteString("// CODE GENERATED BY cmd/genenums. DO NOT EDIT BY HAND.\n")
	b.WriteString("//\n")
	b.WriteString("// Source: Go typed-const enum blocks (AIProviderType, AIErrorKind in\n")
	b.WriteString("// backend/ai; IPCErrorCode and EventName in package main). Regenerate via\n")
	b.WriteString("// `go run -tags tools ./cmd/genenums/ -update frontend/src/generated/enums.ts`\n")
	b.WriteString("// after changing a Go const. The CI drift gate (-compare) fails on drift.\n\n")

	// Collect per-file parses so a file shared by multiple sources is parsed once.
	fileCache := map[string][]*ast.GenDecl{}
	constBlocks := func(path string) ([]*ast.GenDecl, error) {
		if c, ok := fileCache[path]; ok {
			return c, nil
		}
		full := filepath.Join(root, filepath.FromSlash(path))
		src, err := os.ReadFile(full)
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", path, err)
		}
		fset := token.NewFileSet()
		file, err := parser.ParseFile(fset, full, src, parser.ParseComments)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", path, err)
		}
		var blocks []*ast.GenDecl
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.CONST {
				continue
			}
			blocks = append(blocks, gd)
		}
		fileCache[path] = blocks
		return blocks, nil
	}

	for _, src := range enumSources {
		blocks, err := constBlocks(src.File)
		if err != nil {
			return "", err
		}
		consts, err := collectConsts(blocks, src.GoType)
		if err != nil {
			// collectConsts names the const + type; annotate with the source
			// file so the message is actionable when the gate trips.
			return "", fmt.Errorf("%s: %w", src.File, err)
		}
		if len(consts) == 0 {
			return "", fmt.Errorf("no consts of type %s found in %s", src.GoType, src.File)
		}
		writeEnum(&b, src.GoType, consts)
	}

	// writeEnum ends each section with a blank-line separator; the final
	// section should carry no trailing blank line, so trim the run of
	// trailing newlines and reinstate exactly one (matches Prettier's
	// "final newline" convention and the committed file's tail byte-for-byte).
	out := strings.TrimRight(b.String(), "\n") + "\n"
	return out, nil
}

// collectConsts walks parenthesized const blocks and returns every const whose
// (explicit or inherited) declared type matches goType, preserving source order.
// Go semantics: within a parenthesized const declaration, a ValueSpec that
// omits the type inherits the type of the preceding spec in the same block.
//
// A ValueSpec may declare several consts in parallel (`A, B Foo = "x", "y"`):
// vs.Names and vs.Values are parallel slices, so we pair them up to
// min(len(Names), len(Values)) and emit one constEntry per pair.
//
// Every emitted const must be backed by a string literal — these enums are
// string-valued by construction, so a non-string-literal value (iota, const
// alias, …) means the generator cannot faithfully emit it. Returning an error
// here keeps the output complete so the drift gate can catch any change; a
// silent skip would let both committed + regenerated output miss the const
// with no signal. A type-only spec (len(Values) == 0, the iota-inheritance
// form `B Foo` after an iota expression) has no value to emit and is skipped
// without error.
func collectConsts(blocks []*ast.GenDecl, goType string) ([]constEntry, error) {
	var out []constEntry
	for _, gd := range blocks {
		// lastType tracks the inherited type across specs in THIS block only.
		lastType := ""
		for _, spec := range gd.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			if vs.Type != nil {
				if id, ok := vs.Type.(*ast.Ident); ok {
					lastType = id.Name
				}
			}
			if lastType != goType {
				continue
			}
			if len(vs.Names) == 0 {
				continue
			}
			// Type-only spec (no value list, e.g. `B Foo` carrying an iota
			// expression forward): nothing to emit, skip gracefully.
			if len(vs.Values) == 0 {
				continue
			}
			// Names and Values are parallel slices; pair them up to min length
			// so a multi-name spec emits one entry per declared const.
			n := len(vs.Names)
			if len(vs.Values) < n {
				n = len(vs.Values)
			}
			for i := 0; i < n; i++ {
				lit, ok := vs.Values[i].(*ast.BasicLit)
				if !ok || lit.Kind != token.STRING {
					// String-typed enums must be backed by string literals; a
					// non-literal can't be faithfully emitted and would let the
					// drift gate miss a missing const. Fail loud.
					return nil, fmt.Errorf(
						"const %s of type %s has a non-string-literal value (only string literals are supported)",
						vs.Names[i].Name, goType,
					)
				}
				val, err := strconv.Unquote(lit.Value)
				if err != nil {
					return nil, fmt.Errorf("const %s of type %s: unquote %s: %w",
						vs.Names[i].Name, goType, lit.Value, err)
				}
				out = append(out, constEntry{Name: vs.Names[i].Name, Value: val})
			}
		}
	}
	return out, nil
}

// printWidth is Prettier's default line cap. Lines longer than this wrap.
const printWidth = 80

// writeEnum emits one TS const object + derived union type + sorted Names array
// for the enum, matching the project's .prettierrc (singleQuote, trailingComma:
// 'none', tabWidth: 2, semi: false, printWidth: 80) so -update output is
// byte-identical to a Prettier-formatted file. Source order is preserved for
// the object members; Names is sorted for stable consumer iteration.
func writeEnum(b *strings.Builder, goType string, consts []constEntry) {
	fmt.Fprintf(b, "// %s — generated from the Go const block. Do not edit by hand.\n", goType)

	// Object: one member per line, comma after every member except the last
	// (trailingComma: 'none' in .prettierrc).
	fmt.Fprintf(b, "export const %s = {\n", goType)
	for i, c := range consts {
		comma := ","
		if i == len(consts)-1 {
			comma = ""
		}
		fmt.Fprintf(b, "  %s: %s%s\n", c.Name, tsString(c.Value), comma)
	}
	b.WriteString("} as const\n\n")

	// Union type: one line if it fits within printWidth, else wrap after `=`
	// with a 2-space-indented continuation (Prettier's break style for this
	// exact shape).
	typeOneLine := fmt.Sprintf("export type %s = (typeof %s)[keyof typeof %s]", goType, goType, goType)
	if len(typeOneLine) <= printWidth {
		fmt.Fprintf(b, "%s\n\n", typeOneLine)
	} else {
		fmt.Fprintf(b, "export type %s =\n  (typeof %s)[keyof typeof %s]\n\n", goType, goType, goType)
	}

	// Names array: sorted; one line if it fits, else multi-line with one
	// entry per line (2-space indent, no trailing comma on the last entry).
	names := make([]string, 0, len(consts))
	for _, c := range consts {
		names = append(names, c.Name)
	}
	sort.Strings(names)
	quoted := make([]string, len(names))
	for i, n := range names {
		quoted[i] = tsString(n)
	}
	namesOneLine := fmt.Sprintf("export const %sNames = [%s] as const", goType, strings.Join(quoted, ", "))
	if len(namesOneLine) <= printWidth {
		fmt.Fprintf(b, "%s\n\n", namesOneLine)
	} else {
		fmt.Fprintf(b, "export const %sNames = [\n", goType)
		for i, q := range quoted {
			comma := ","
			if i == len(quoted)-1 {
				comma = ""
			}
			fmt.Fprintf(b, "  %s%s\n", q, comma)
		}
		b.WriteString("] as const\n\n")
	}
}

// tsString renders a Go-extracted string as a single-quoted TS string literal
// (.prettierrc singleQuote: true). Escape backslash and single quote; the
// current value set is simple ASCII so neither escape fires, but keep the
// generator correct if one ever does.
func tsString(s string) string {
	r := strings.NewReplacer("\\", "\\\\", "'", "\\'")
	return "'" + r.Replace(s) + "'"
}
