//go:build tools

// Command genenums parses the four canonical Go typed-const enum blocks and
// emits one TypeScript module (frontend/src/generated/enums.ts) so the frontend
// consumes generated values instead of re-typing bare string literals.
//
// Why a parallel generator (not Wails's own `wails3 generate bindings`)? Wails
// v3 only emits typed-const enums when the named type is reachable from a bound
// service method's type graph. These four families are not reachable there:
// AIProviderType/AIErrorKind are reachable only through error-returning types
// (serialized as strings), IPCErrorCode lives on *IPCError (an error type), and
// EventName is a pure constant set with no struct field. Forcing reachability
// would pollute the IPC surface that cmd/inventory gates. Parsing the Go const
// blocks directly (go/ast) keeps the IPC surface clean and Go the single source
// of truth. See docs/decisions/ for the full ADR.
//
// Modes (selected by flag):
//
//	# Print the generated module to stdout (ad-hoc inspection):
//	go run -tags tools ./cmd/genenums/
//
//	# Write the module to the committed FE path (regenerate after an intentional
//	# enum change). Re-run -compare afterwards to confirm parity.
//	go run -tags tools ./cmd/genenums/ -update frontend/src/generated/enums.ts
//
//	# CI drift gate: regenerate to memory and compare against the committed file;
//	# exit 1 on any drift (a Go const changed/added/removed without regenerating).
//	go run -tags tools ./cmd/genenums/ -compare frontend/src/generated/enums.ts
//
// The output is deterministic (consts are emitted in source order), so the drift
// gate is byte-stable across platforms.
package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// enumSource pairs a Go named type with the file that declares its const block.
// Order controls the TS export order (stable).
var enumSources = []enumSource{
	{GoType: "AIProviderType", File: "backend/ai/service.go"},
	{GoType: "AIErrorKind", File: "backend/ai/service.go"},
	{GoType: "IPCErrorCode", File: "ipc_errors.go"},
	{GoType: "EventName", File: "events.go"},
}

type enumSource struct {
	GoType string
	File   string
}

// constEntry is one Go const (Name → string Value) belonging to an enum type.
type constEntry struct {
	Name  string
	Value string
}

func main() {
	out := flag.String("update", "", "write the generated module to this path (regenerate after an intentional enum change)")
	compare := flag.String("compare", "", "compare the generated module against the file at this path; exit 1 on drift")
	flag.Usage = func() {
		fmt.Fprintf(flag.CommandLine.Output(),
			"usage: genenums [flags] [repo-root]\n\n  flags:\n    -update <path>\n    -compare <path>\n")
		flag.PrintDefaults()
	}
	flag.Parse()
	root := flag.Arg(0)
	if root == "" {
		root = "."
	}

	module, err := generate(root)
	if err != nil {
		fmt.Fprintln(os.Stderr, "genenums:", err)
		os.Exit(1)
	}

	switch {
	case *out != "":
		if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
			fmt.Fprintln(os.Stderr, "genenums: mkdir:", err)
			os.Exit(1)
		}
		if err := os.WriteFile(*out, []byte(module), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "genenums: write:", err)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "genenums: module written to %s\n", *out)
	case *compare != "":
		want, err := os.ReadFile(*compare)
		if err != nil {
			fmt.Fprintln(os.Stderr, "genenums: read fixture:", err)
			os.Exit(1)
		}
		if string(want) != module {
			fmt.Fprintf(os.Stderr,
				"genenums: DRIFT — %s does not match the generated module.\n"+
					"Regenerate with: go run -tags tools ./cmd/genenums/ -update %s\n",
				*compare, *compare)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "genenums: %s up to date\n", *compare)
	default:
		fmt.Print(module)
	}
}

// generate builds the TS module string from the four Go const blocks under root.
func generate(root string) (string, error) {
	var b strings.Builder
	b.WriteString("// CODE GENERATED BY cmd/genenums. DO NOT EDIT BY HAND.\n")
	b.WriteString("//\n")
	b.WriteString("// Source: Go typed-const enum blocks (AIProviderType, AIErrorKind in\n")
	b.WriteString("// backend/ai; IPCErrorCode and EventName in package main). Regenerate via\n")
	b.WriteString("// `go run -tags tools ./cmd/genenums/ -update frontend/src/generated/enums.ts`\n")
	b.WriteString("// after changing a Go const. The CI drift gate (-compare) fails on drift.\n\n")

	// Collect per-file parses so a file shared by multiple sources is parsed once.
	fileCache := map[string][]*ast.GenDecl{}
	constBlocks := func(path string) ([]*ast.GenDecl, error) {
		if c, ok := fileCache[path]; ok {
			return c, nil
		}
		full := filepath.Join(root, filepath.FromSlash(path))
		src, err := os.ReadFile(full)
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", path, err)
		}
		fset := token.NewFileSet()
		file, err := parser.ParseFile(fset, full, src, parser.ParseComments)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", path, err)
		}
		var blocks []*ast.GenDecl
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.CONST {
				continue
			}
			blocks = append(blocks, gd)
		}
		fileCache[path] = blocks
		return blocks, nil
	}

	for _, src := range enumSources {
		blocks, err := constBlocks(src.File)
		if err != nil {
			return "", err
		}
		consts := collectConsts(blocks, src.GoType)
		if len(consts) == 0 {
			return "", fmt.Errorf("no consts of type %s found in %s", src.GoType, src.File)
		}
		writeEnum(&b, src.GoType, consts)
	}

	return b.String(), nil
}

// collectConsts walks parenthesized const blocks and returns every const whose
// (explicit or inherited) declared type matches goType, preserving source order.
// Go semantics: within a parenthesized const declaration, a ValueSpec that
// omits the type inherits the type of the preceding spec in the same block.
func collectConsts(blocks []*ast.GenDecl, goType string) []constEntry {
	var out []constEntry
	for _, gd := range blocks {
		// lastType tracks the inherited type across specs in THIS block only.
		lastType := ""
		for _, spec := range gd.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			if vs.Type != nil {
				if id, ok := vs.Type.(*ast.Ident); ok {
					lastType = id.Name
				}
			}
			if lastType != goType {
				continue
			}
			if len(vs.Names) == 0 || len(vs.Values) == 0 {
				continue
			}
			lit, ok := vs.Values[0].(*ast.BasicLit)
			if !ok || lit.Kind != token.STRING {
				// Non-string-literal const (e.g. an iota); skip — these enums are
				// all string-valued by construction.
				continue
			}
			val, err := strconv.Unquote(lit.Value)
			if err != nil {
				continue
			}
			out = append(out, constEntry{Name: vs.Names[0].Name, Value: val})
		}
	}
	return out
}

// writeEnum emits one TS const object + derived union type for the enum.
func writeEnum(b *strings.Builder, goType string, consts []constEntry) {
	fmt.Fprintf(b, "// %s — generated from the Go const block. Do not edit by hand.\n", goType)
	fmt.Fprintf(b, "export const %s = {\n", goType)
	// Source order is preserved (deterministic); the values are already in
	// declaration order from collectConsts.
	names := make([]string, 0, len(consts))
	for _, c := range consts {
		fmt.Fprintf(b, "  %s: %s,\n", c.Name, tsString(c.Value))
		names = append(names, c.Name)
	}
	b.WriteString("} as const\n\n")
	fmt.Fprintf(b, "export type %s = (typeof %s)[keyof typeof %s]\n\n", goType, goType, goType)
	// A sorted name list helps consumers iterate without re-deriving keys.
	sort.Strings(names)
	fmt.Fprintf(b, "export const %sNames = [%s] as const\n\n", goType, quoteList(names))
}

// tsString renders a Go-extracted string as a double-quoted TS string literal.
// All enum values are simple ASCII ([a-z0-9:-]); strconv.Quote's escaping is a
// TS-compatible subset for these, but we re-quote explicitly to avoid any
// locale/slash surprises.
func tsString(s string) string {
	// Use double quotes; escape backslash and double-quote (none appear in the
	// current value sets, but keep the generator correct if one ever does).
	r := strings.NewReplacer("\\", "\\\\", "\"", "\\\"")
	return "\"" + r.Replace(s) + "\""
}

// quoteList renders a comma-separated list of quoted TS string literals.
func quoteList(names []string) string {
	parts := make([]string, len(names))
	for i, n := range names {
		parts[i] = tsString(n)
	}
	return strings.Join(parts, ", ")
}
