// FE Flatten golden parity vs Go Theme.Flatten (#530).
// Goldens live in __fixtures__/flatten-goldens/ (generated by Go
// TestFlatten_GoldenParity with UPDATE_GOLDENS=1). Theme JSON is read from
// backend/themes/themes/*.json — the same embed source Go uses.
//
// When Flatten changes intentionally:
//   UPDATE_GOLDENS=1 go test ./backend/themes/ -run TestFlatten_GoldenParity
// then re-run this suite (both sides must match the same files).

import { describe, expect, it } from 'vitest'
import { readdirSync, readFileSync } from 'node:fs'
import { resolve, basename } from 'node:path'
import { flattenTheme } from './flatten'
import type { ThemeDoc, ThemeModeKey } from './types'

const themesDir = resolve(__dirname, '../../../backend/themes/themes')
const goldensDir = resolve(__dirname, '__fixtures__/flatten-goldens')

function loadTheme(id: string): ThemeDoc {
  const raw = readFileSync(resolve(themesDir, `${id}.json`), 'utf8')
  return JSON.parse(raw) as ThemeDoc
}

function loadGolden(id: string, mode: ThemeModeKey): Record<string, string> {
  const raw = readFileSync(resolve(goldensDir, `${id}.${mode}.json`), 'utf8')
  return JSON.parse(raw) as Record<string, string>
}

function sortedKeys(m: Record<string, string>): string[] {
  return Object.keys(m).sort()
}

const themeFiles = readdirSync(themesDir).filter((f) => f.endsWith('.json'))
const themeIds = themeFiles.map((f) => basename(f, '.json')).sort()

describe('flattenTheme golden parity with Go Flatten (#530)', () => {
  it('has goldens for every embedded theme × mode', () => {
    expect(themeIds.length).toBeGreaterThanOrEqual(11)
    for (const id of themeIds) {
      for (const mode of ['dark', 'light'] as const) {
        expect(() => loadGolden(id, mode)).not.toThrow()
      }
    }
  })

  for (const id of themeIds) {
    for (const mode of ['dark', 'light'] as const) {
      it(`${id} ${mode}`, () => {
        const doc = loadTheme(id)
        const got = flattenTheme(doc, mode)
        const want = loadGolden(id, mode)
        expect(sortedKeys(got)).toEqual(sortedKeys(want))
        for (const k of sortedKeys(want)) {
          expect(got[k], k).toBe(want[k])
        }
      })
    }
  }
})
